package com.project.code.Model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;


@Entity
public class Inventory {

    /*-------------Private Attributes-------------*/
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @JsonBackReference("inventory-product")
    @OneToMany
    @JoinColumn(name = "product_id") //the owner of the column is Product since you can't have a stock of something that doesn't exist.  That's why this attribute is a FK
    private Product product;

    @JoinColumn(name = "store_id") //the owner of the column is Store since it's the store where the stock of a product is stored. That's why this attribute is a FK
    @JsonBackReference("inventory-store")
    @ManyToOne()
    private Store store; //the store where the inventory can be found

    private Integer stockLevel; //level of the product at the store

    /*-------------Costructor-------------*/
    //reminder: autogenerated id so
    public Inventory(Product product, Store store, Integer stockLevel) {
        this.product = product;
        this.store = store;
        this.stockLevel = stockLevel;
    }
    /*-------------Getters and setters-------------*/

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public Store getStore() {
        return store;
    }

    public void setStore(Store store) {
        this.store = store;
    }

    public Integer getStockLevel() {
        return stockLevel;
    }

    public void setStockLevel(Integer stockLevel) {
        this.stockLevel = stockLevel;
    }
}

